fixup! Repository
/home/greg/Desktop/src/Open-Table-
Explorer/test/assertions/repository_assertions.rb:75:in
`<module:Examples>': undefined method `data_sources_directory?' for
Repository:Class (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/assertions/repository_assertions.rb:67:in
`<class:Repository>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/assertions/repository_assertions.rb:10:in `<top
(required)>'
	from test/unit/repository_test.rb:9:in `require_relative'
	from test/unit/repository_test.rb:9:in `<main>'