fixup! Parse
/home/greg/Desktop/src/Open-Table-Explorer/app/models/parse.rb:112:in
`initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/parse.rb:216:in `new'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/parse.rb:216:in `<module:Examples>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/parse.rb:207:in `<class:Parse>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/parse.rb:10:in `<top (required)>'
	from test/unit/parse_test.rb:9:in `require_relative'
	from test/unit/parse_test.rb:9:in `<main>'