fixup! DefaultTestCase
/home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:68:in `<module:DefaultTests0>':
undefined method `model_name?' for DefaultTests0:Module (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:64:in `<top (required)>'
	from test/unit/default_test_case_test.rb:9:in `require_relative'
	from test/unit/default_test_case_test.rb:9:in `<main>'