fixup! FilePattern
/home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:59:in `block in project_root_dir?':
undefined method `pre_match' for nil:NilClass (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:57:in `map'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:57:in `project_root_dir?'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:85:in `<module:Constants>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:84:in `<class:FilePattern>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:12:in `<top (required)>'
	from test/unit/file_pattern_test.rb:12:in `require_relative'
	from test/unit/file_pattern_test.rb:12:in `<main>'