fixup! work_flow
edited

ruby -v -W0 test/unit/work_flow_test.rb
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
Run options:

..........E...E.....merge(:edited, :testing, :interactive)
merge_status= $ git merge testing
@process_status=#<Process::Status: pid 28760 exit 1>
Auto-merging test/unit/work_flow_test.rb
CONFLICT (content): Merge conflict in test/unit/work_flow_test.rb
Auto-merging test/unit/unit_maturity_test.rb
CONFLICT (add/add): Merge conflict in test/unit/unit_maturity_test.rb
Auto-merging test/unit/tax_form_test.rb
Auto-merging test/unit/branch_test.rb
CONFLICT (content): Merge conflict in test/unit/branch_test.rb
Auto-merging script/work_flow.rb
Auto-merging log/unit/1.9/1.9.3p194/quiet/work_flow.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/work_flow.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/testing.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/testing.rb.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/minimal2.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/minimal2.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
Auto-merging app/models/work_flow.rb
CONFLICT (content): Merge conflict in app/models/work_flow.rb
Auto-merging app/models/tax_form.rb
CONFLICT (content): Merge conflict in app/models/tax_form.rb
Auto-merging app/models/repository.rb
Automatic merge failed; fix conflicts and then commit the result.
merge_conflict_recovery$ git merge testing
@process_status=#<Process::Status: pid 28760 exit 1>
Auto-merging test/unit/work_flow_test.rb
CONFLICT (content): Merge conflict in test/unit/work_flow_test.rb
Auto-merging test/unit/unit_maturity_test.rb
CONFLICT (add/add): Merge conflict in test/unit/unit_maturity_test.rb
Auto-merging test/unit/tax_form_test.rb
Auto-merging test/unit/branch_test.rb
CONFLICT (content): Merge conflict in test/unit/branch_test.rb
Auto-merging script/work_flow.rb
Auto-merging log/unit/1.9/1.9.3p194/quiet/work_flow.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/work_flow.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/testing.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/testing.rb.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/minimal2.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/minimal2.log
Auto-merging log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
CONFLICT (content): Merge conflict in
log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
Auto-merging app/models/work_flow.rb
CONFLICT (content): Merge conflict in app/models/work_flow.rb
Auto-merging app/models/tax_form.rb
CONFLICT (content): Merge conflict in app/models/tax_form.rb
Auto-merging app/models/repository.rb
Automatic merge failed; fix conflicts and then commit the result.
ruby script/workflow.rb --test app/models/repository.rb
ruby script/workflow.rb --test app/models/shell_command.rb
ruby script/workflow.rb --test app/models/tax_form.rb
ruby script/workflow.rb --test app/models/work_flow.rb
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
ruby script/workflow.rb --test log/unit/1.9/1.9.3p194/quiet/minimal2.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/testing.rb.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/work_flow.log
ruby script/workflow.rb --test script/work_flow.rb
ruby script/workflow.rb --test test/assertions/ruby_assertions.rb
ruby script/workflow.rb --test test/unit/branch_test.rb
ruby script/workflow.rb --test test/unit/repository_test.rb
ruby script/workflow.rb --test test/unit/tax_form_test.rb
ruby script/workflow.rb --test test/unit/unit_maturity_test.rb
ruby script/workflow.rb --test test/unit/work_flow_test.rb
@repository.merge_conflict_files?= [{:conflict=>"M ",
:file=>"app/models/repository.rb"}, {:conflict=>"M ",
:file=>"app/models/shell_command.rb"}, {:conflict=>"UU",
:file=>"app/models/tax_form.rb"}, {:conflict=>"UU",
:file=>"app/models/work_flow.rb"}, {:conflict=>"UU",
:file=>"log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log"},
{:conflict=>"UU", :file=>"log/unit/1.9/1.9.3p194/quiet/minimal2.log"},
{:conflict=>"UU",
:file=>"log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log"},
{:conflict=>"UU", :file=>"log/unit/1.9/1.9.3p194/quiet/testing.rb.log"},
{:conflict=>"UU", :file=>"log/unit/1.9/1.9.3p194/quiet/work_flow.log"},
{:conflict=>"M ", :file=>"script/work_flow.rb"}, {:conflict=>"M ",
:file=>"test/assertions/ruby_assertions.rb"}, {:conflict=>"UU",
:file=>"test/unit/branch_test.rb"}, {:conflict=>"M ",
:file=>"test/unit/repository_test.rb"}, {:conflict=>"M ",
:file=>"test/unit/tax_form_test.rb"}, {:conflict=>"AA",
:file=>"test/unit/unit_maturity_test.rb"}, {:conflict=>"UU",
:file=>"test/unit/work_flow_test.rb"}]
ruby script/workflow.rb --test app/models/repository.rb
ruby script/workflow.rb --test app/models/shell_command.rb
ruby script/workflow.rb --test app/models/tax_form.rb
ruby script/workflow.rb --test app/models/work_flow.rb
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
ruby script/workflow.rb --test log/unit/1.9/1.9.3p194/quiet/minimal2.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/testing.rb.log
ruby script/workflow.rb --test
log/unit/1.9/1.9.3p194/quiet/work_flow.log
ruby script/workflow.rb --test script/work_flow.rb
ruby script/workflow.rb --test test/assertions/ruby_assertions.rb
ruby script/workflow.rb --test test/unit/branch_test.rb
ruby script/workflow.rb --test test/unit/repository_test.rb
ruby script/workflow.rb --test test/unit/tax_form_test.rb
ruby script/workflow.rb --test test/unit/unit_maturity_test.rb
ruby script/workflow.rb --test test/unit/work_flow_test.rb
merge --abort
merge --X ours testing
not checkout HEAD app/models/repository.rb
not checkout HEAD app/models/shell_command.rb
not checkout HEAD app/models/tax_form.rb
not checkout HEAD app/models/work_flow.rb
checkout HEAD log/unit/1.9/1.9.3p194/quiet/initialization_fail.rb.log
checkout HEAD log/unit/1.9/1.9.3p194/quiet/minimal2.log
checkout HEAD log/unit/1.9/1.9.3p194/quiet/single_test_fail.rb.log
checkout HEAD log/unit/1.9/1.9.3p194/quiet/testing.rb.log
checkout HEAD log/unit/1.9/1.9.3p194/quiet/work_flow.log
not checkout HEAD script/work_flow.rb
not checkout HEAD test/assertions/ruby_assertions.rb
not checkout HEAD test/unit/branch_test.rb
not checkout HEAD test/unit/repository_test.rb
not checkout HEAD test/unit/tax_form_test.rb
not checkout HEAD test/unit/unit_maturity_test.rb
E$ ruby  script/work_flow.rb --merge-down
@errors="/home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:230:in `merge_down': undefined method
`merge_range' for UnitMaturity:Class (NoMethodError)\n\tfrom
script/work_flow.rb:114:in `block in <main>'\n\tfrom
script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in
`<main>'\n"
@process_status=#<Process::Status: pid 29786 exit 1>
$ echo "Hello World"
Hello World
$ echo "1 2;3 4"
1 2;3 4
$ $?=1
@errors="sh: 1: 0=1: not found\n"
@process_status=#<Process::Status: pid 29828 exit 127>
$ ls happyHappyFailFail.junk
@errors="ls: cannot access happyHappyFailFail.junk: No such file or
directory\n"
@process_status=#<Process::Status: pid 29831 exit 2>
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
work_flow --<command> <file>
F...F........

Finished tests in 8921.472826s, 0.0038 tests/s, 0.5631 assertions/s.

1) Error:
test_deserving_branch?(WorkFlowTest):
NameError: uninitialized constant
WorkFlowTest::Deserving_commit_to_branch
    test/unit/work_flow_test.rb:100:in `block in test_deserving_branch?'
    test/unit/work_flow_test.rb:92:in `each_pair'
    test/unit/work_flow_test.rb:92:in `test_deserving_branch?'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:1058:in `run'
    /usr/lib/ruby/1.9.1/test/unit/testcase.rb:17:in `run'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:36:in
`block in run'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:403:in
`_run__3211091616572199280__setup__1898633883656943326__callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in
`__run_callback'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in
`_run_setup_callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in
`run_callbacks'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:35:in
`run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:823:in `block in
_run_suite'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `map'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `_run_suite'
    /usr/lib/ruby/1.9.1/test/unit.rb:565:in `block in _run_suites'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `each'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `_run_suites'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:775:in `_run_anything'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:964:in `run_tests'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:951:in `block in _run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `each'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `_run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:939:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in
autorun'
    /usr/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    /usr/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'

2) Error:
test_goldilocks(WorkFlowTest):
NoMethodError: undefined method `branch_index?' for WorkFlow:Class
    test/unit/work_flow_test.rb:59:in `test_goldilocks'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:1058:in `run'
    /usr/lib/ruby/1.9.1/test/unit/testcase.rb:17:in `run'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:36:in
`block in run'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:403:in
`_run__3211091616572199280__setup__1898633883656943326__callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in
`__run_callback'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in
`_run_setup_callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in
`run_callbacks'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:35:in
`run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:823:in `block in
_run_suite'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `map'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `_run_suite'
    /usr/lib/ruby/1.9.1/test/unit.rb:565:in `block in _run_suites'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `each'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `_run_suites'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:775:in `_run_anything'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:964:in `run_tests'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:951:in `block in _run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `each'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `_run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:939:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in
autorun'
    /usr/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    /usr/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'

3) Error:
test_merge(WorkFlowTest):
Exception: {:conflict=>"AA", :file=>"test/unit/unit_maturity_test.rb"}
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:160:in `block in
merge_conflict_recovery'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:142:in `each'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:142:in `merge_conflict_recovery'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:185:in `block in merge'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/repository.rb:272:in `call'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/repository.rb:272:in `safely_visit_branch'
    /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:175:in `merge'
    test/unit/work_flow_test.rb:116:in `test_merge'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:1058:in `run'
    /usr/lib/ruby/1.9.1/test/unit/testcase.rb:17:in `run'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:36:in
`block in run'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:403:in
`_run__3211091616572199280__setup__1898633883656943326__callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in
`__run_callback'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in
`_run_setup_callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in
`run_callbacks'

/usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:35:in
`run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:823:in `block in
_run_suite'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `map'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `_run_suite'
    /usr/lib/ruby/1.9.1/test/unit.rb:565:in `block in _run_suites'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `each'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `_run_suites'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:775:in `_run_anything'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:964:in `run_tests'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:951:in `block in _run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `each'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `_run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:939:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in
autorun'
    /usr/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    /usr/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'

4) Failure:
test_merge_command(WorkFlowTest) [test/unit/work_flow_test.rb:155]:
self=$ ruby  script/work_flow.rb --merge-down
@errors="/home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:230:in `merge_down': undefined method
`merge_range' for UnitMaturity:Class (NoMethodError)\n\tfrom
script/work_flow.rb:114:in `block in <main>'\n\tfrom
script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in
`<main>'\n"
@process_status=#<Process::Status: pid 29786 exit 1>
$ echo "Hello World"
Hello World
$ echo "1 2;3 4"
1 2;3 4
$ $?=1
@errors="sh: 1: 0=1: not found\n"
@process_status=#<Process::Status: pid 29828 exit 127>
$ ls happyHappyFailFail.junk
@errors="ls: cannot access happyHappyFailFail.junk: No such file or
directory\n"
@process_status=#<Process::Status: pid 29831 exit 2>
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
work_flow --<command> <file>
expected errors to be empty\n
"/home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:230:in `merge_down': undefined method
`merge_range' for UnitMaturity:Class (NoMethodError)\n\tfrom
script/work_flow.rb:114:in `block in <main>'\n\tfrom
script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in
`<main>'\n" is not empty.

5) Failure:
test_minimal_comparison(WorkFlowTest) [test/unit/work_flow_test.rb:85]:
<" -t app/models/work_flow.rb app/models/minimal2.rb -t
test/unit/work_flow_test.rb test/unit/minimal2_test.rb -t
script/work_flow.rb script/minimal2.rb -t
test/integration/work_flow_test.rb test/integration/minimal2_test.rb -t
test/long_test/work_flow_test.rb test/long_test/minimal2_test.rb -t
test/assertions/work_flow_assertions.rb
test/assertions/minimal2_assertions.rb -t
test/unit/work_flow_assertions_test.rb
test/unit/minimal2_assertions_test.rb -t log/library/work_flow.log
log/library/minimal2.log -t log/assertions/work_flow.log
log/assertions/minimal2.log -t log/integration/work_flow.log
log/integration/minimal2.log -t log/long/work_flow.log
log/long/minimal2.log -t test/data_sources/work_flow
test/data_sources/minimal2"> expected but was
<" -t app/models/work_flow.rb app/models/minimal2.rb -t
test/unit/work_flow_test.rb test/unit/minimal2_test.rb">.

34 tests, 5024 assertions, 2 failures, 3 errors, 0 skips