fixup! WorkFlow
/home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:223:in
`<class:DefaultTestCase0>': undefined method `model_name?' for
DefaultTestCase0:Class (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:197:in `<top (required)>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment_default_test_case.rb:9:in
`require_relative'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment_default_test_case.rb:9:in `<top
(required)>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment.rb:8:in `require_relative'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment.rb:8:in `<top (required)>'
	from test/unit/work_flow_test.rb:8:in `require_relative'
	from test/unit/work_flow_test.rb:8:in `<main>'