fixup! TaxForm
/home/greg/Desktop/src/Open-Table-Explorer/app/models/tax_form.rb:20:in
`<module:Constants>': undefined method `project_root_dir?' for
#<FilePattern:0x940c690> (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/tax_form.rb:18:in `<module:Finance>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/tax_form.rb:17:in `<module:OpenTableExplorer>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/tax_form.rb:14:in `<top (required)>'
	from test/unit/tax_form_test.rb:9:in `require_relative'
	from test/unit/tax_form_test.rb:9:in `<main>'