fixup! Repository
/home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:116:in `sub_directory_match':
undefined method `match' for nil:NilClass (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:46:in `block in path2model_name?'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:45:in `map'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/file_pattern.rb:45:in `path2model_name?'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/related_file.rb:21:in `initialize'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/related_file.rb:183:in `new'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/related_file.rb:183:in `<module:Examples>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/related_file.rb:180:in `<class:RelatedFile>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/related_file.rb:9:in `<top (required)>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment_default_test_case.rb:13:in
`require_relative'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment_default_test_case.rb:13:in `<top
(required)>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment.rb:8:in `require_relative'
	from /home/greg/Desktop/src/Open-Table-
Explorer/test/unit/test_environment.rb:8:in `<top (required)>'
	from test/unit/repository_test.rb:8:in `require_relative'
	from test/unit/repository_test.rb:8:in `<main>'