fixup! WorkFlow
/home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:40:in
`initialize': undefined local variable or method `argv' for
#<WorkFlow:0x8ad1af8> (NameError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:222:in `new'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:222:in `<module:Examples>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:220:in `<class:WorkFlow>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:13:in `<top (required)>'
	from test/unit/work_flow_test.rb:9:in `require_relative'
	from test/unit/work_flow_test.rb:9:in `<main>'