fixup! WorkFlow
/home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:47:in
`initialize': undefined method `current_branch?' for
#<Repository:0x8858858> (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:227:in `new'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:227:in `<module:Examples>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:225:in `<class:WorkFlow>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:13:in `<top (required)>'
	from test/unit/work_flow_test.rb:9:in `require_relative'
	from test/unit/work_flow_test.rb:9:in `<main>'