fixup! work_flow
master

ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
Run options:

......F........E..............F...FE......F
2) Error:
test_differences?(WorkFlowTest):
RuntimeError: test/long_test/repository_test.rb does not exist.
    app/models/work_flow.rb:110:in `diff_command?'
    app/models/work_flow.rb:124:in `working_different_from?'
    test/unit/work_flow_test.rb:127:in `test_differences?'

3) Failure:
test_minimal_comparison(WorkFlowTest) [test/unit/work_flow_test.rb:211]:
<" -t app/models/work_flow.rb app/models/minimal2.rb -t
test/unit/work_flow_test.rb test/unit/minimal2_test.rb -t
script/work_flow.rb script/minimal2.rb -t
test/integration/work_flow_test.rb test/integration/minimal2_test.rb -t
test/long_test/work_flow_test.rb test/long_test/minimal2_test.rb -t
test/assertions/work_flow_assertions.rb
test/assertions/minimal2_assertions.rb -t
test/unit/work_flow_assertions_test.rb
test/unit/minimal2_assertions_test.rb -t log/library/work_flow.log
log/library/minimal2.log -t log/assertions/work_flow.log
log/assertions/minimal2.log -t log/integration/work_flow.log
log/integration/minimal2.log -t log/long/work_flow.log
log/long/minimal2.log -t test/data_sources/work_flow
test/data_sources/minimal2"> expected but was
<" -t app/models/work_flow.rb app/models/minimal2.rb -t
test/unit/work_flow_test.rb test/unit/minimal2_test.rb">.

4) Failure:
test_revison_tag?(WorkFlowTest) [test/unit/work_flow_test.rb:71]:
<"-r origin/master"> expected but was
<"-r work_flow">.

5) Error:
test_scan_verions?(WorkFlowTest):
RuntimeError: test/long_test/repository_test.rb does not exist.
    app/models/work_flow.rb:110:in `diff_command?'
    app/models/work_flow.rb:124:in `working_different_from?'
    app/models/work_flow.rb:135:in `block in differences?'
    app/models/work_flow.rb:134:in `each'
    app/models/work_flow.rb:134:in `map'
    app/models/work_flow.rb:134:in `differences?'
    test/unit/work_flow_test.rb:139:in `test_scan_verions?'

6) Failure:
test_working_different_from?(WorkFlowTest)
[test/unit/work_flow_test.rb:120]:
<[]> expected to be != to
<[]>.

43 tests, 5246 assertions, 4 failures, 2 errors, 0 skips