fixup! WorkFlow
/home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:38:in
`initialize': undefined method `project_root_dir' for nil:NilClass
(NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:221:in `new'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:221:in `<module:Examples>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:219:in `<class:WorkFlow>'
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/work_flow.rb:13:in `<top (required)>'
	from test/unit/work_flow_test.rb:9:in `require_relative'
	from test/unit/work_flow_test.rb:9:in `<main>'