fixup! DefaultTestCase
/home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:223:in
`<class:DefaultTestCase0>': undefined method `model_name?' for
DefaultTestCase0:Class (NoMethodError)
	from /home/greg/Desktop/src/Open-Table-
Explorer/app/models/default_test_case.rb:197:in `<top (required)>'
	from test/unit/default_test_case_test.rb:9:in `require_relative'
	from test/unit/default_test_case_test.rb:9:in `<main>'